on:
  push:
    branches:
      - main
name: 🚀 Building Linux
jobs:
  kernel-build:
    name: 🎉 Building All Variants
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Compiling kernel stable
      run: |
          wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.2.2.tar.xz
          tar -xvf linux-6.2.2.tar.xz
          cd linux-6.2.2 || exit
          cp ../kernel_config/defconfig .config
          make -j$(nproc)
    # - name: 🚀 Building Linux Zen
    #   run: |
    #       git clone https://github.com/zen-kernel/zen-kernel.git src/linux
    #       cd src/linux || exit
    #       cp ../../kernel_config/defconfig .config
    #       make -j$(nproc)
    - name: 🚀 Building Linux Xanmod
      run: |
          git clone https://github.com/xanmod/linux.git
          cd linux || exit
          cp ../kernel_config/xanmod .config
          make -j$(nproc)
